// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Models;

namespace backend.Migrations
{
    [DbContext(typeof(FBlogAcademyContext))]
    [Migration("20231115151439_InitialDB")]
    partial class InitialDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("backend.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdminId")
                        .HasColumnType("int")
                        .HasColumnName("admin_id");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("category_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("Category");
                });

            modelBuilder.Entity("backend.Models.CategoryTag", b =>
                {
                    b.Property<int>("TagId")
                        .HasColumnType("int")
                        .HasColumnName("tag_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.HasKey("TagId", "CategoryId")
                        .HasName("PK__Category__1FC24C2D619EB0CA");

                    b.HasIndex("CategoryId");

                    b.ToTable("CategoryTag");
                });

            modelBuilder.Entity("backend.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("PostId")
                        .HasColumnType("int")
                        .HasColumnName("post_id");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("backend.Models.FollowUser", b =>
                {
                    b.Property<int>("FollowerId")
                        .HasColumnType("int")
                        .HasColumnName("follower_id");

                    b.Property<int>("FollowedId")
                        .HasColumnType("int")
                        .HasColumnName("followed_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.HasKey("FollowerId", "FollowedId")
                        .HasName("PK__FollowUs__838707A38FAF7E83");

                    b.HasIndex("FollowedId");

                    b.ToTable("FollowUser");
                });

            modelBuilder.Entity("backend.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("PostId")
                        .HasColumnType("int")
                        .HasColumnName("post_id");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("backend.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit")
                        .HasColumnName("is_approved");

                    b.Property<int?>("ReviewerId")
                        .HasColumnType("int")
                        .HasColumnName("reviewer_id");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("UserId");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("backend.Models.PostCategory", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("int")
                        .HasColumnName("post_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.HasKey("PostId", "CategoryId")
                        .HasName("PK__PostCate__638369FD4FBDCD1A");

                    b.HasIndex("CategoryId");

                    b.ToTable("PostCategory");
                });

            modelBuilder.Entity("backend.Models.PostList", b =>
                {
                    b.Property<int>("SaveListId")
                        .HasColumnType("int")
                        .HasColumnName("save_list_id");

                    b.Property<int>("SavePostId")
                        .HasColumnType("int")
                        .HasColumnName("save_post_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.HasKey("SaveListId", "SavePostId")
                        .HasName("PK__PostList__859A5D1BB3774C7B");

                    b.HasIndex("SavePostId");

                    b.ToTable("PostList");
                });

            modelBuilder.Entity("backend.Models.PostTag", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("int")
                        .HasColumnName("post_id");

                    b.Property<int>("TagId")
                        .HasColumnType("int")
                        .HasColumnName("tag_id");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.HasKey("PostId", "TagId")
                        .HasName("PK__PostTag__4AFEED4D0915C090");

                    b.HasIndex("TagId");

                    b.ToTable("PostTag");
                });

            modelBuilder.Entity("backend.Models.ReportPost", b =>
                {
                    b.Property<int>("ReporterId")
                        .HasColumnType("int")
                        .HasColumnName("reporter_id");

                    b.Property<int>("PostId")
                        .HasColumnType("int")
                        .HasColumnName("post_id");

                    b.Property<int?>("AdminId")
                        .HasColumnType("int")
                        .HasColumnName("admin_id");

                    b.Property<string>("Content")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("status")
                        .IsFixedLength(true);

                    b.HasKey("ReporterId", "PostId")
                        .HasName("PK__ReportPo__39154D75DD3D3CC7");

                    b.HasIndex("AdminId");

                    b.HasIndex("PostId");

                    b.ToTable("ReportPost");
                });

            modelBuilder.Entity("backend.Models.SaveList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("update_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SaveList");
                });

            modelBuilder.Entity("backend.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdminId")
                        .HasColumnType("int")
                        .HasColumnName("admin_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tag_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("TagName")
                        .IsUnique();

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("email");

                    b.Property<bool>("IsAwarded")
                        .HasColumnType("bit")
                        .HasColumnName("is_awarded");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .HasMaxLength(65)
                        .IsUnicode(false)
                        .HasColumnType("varchar(65)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .HasColumnName("role")
                        .IsFixedLength(true);

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "UQ__User__AB6E6164D120EBFA")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("backend.Models.UserCategory", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.HasKey("UserId", "CategoryId")
                        .HasName("PK__UserCate__638369FD4FBDCD1A");

                    b.HasIndex("CategoryId");

                    b.ToTable("UserCategory");
                });

            modelBuilder.Entity("backend.Models.UserTag", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("TagId")
                        .HasColumnType("int")
                        .HasColumnName("tag_id");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.HasKey("UserId", "TagId")
                        .HasName("PK__UserTag__638369FD4FBDCD1A");

                    b.HasIndex("TagId");

                    b.ToTable("UserTag");
                });

            modelBuilder.Entity("backend.Models.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("PostId")
                        .HasColumnType("int")
                        .HasColumnName("post_id");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Video");
                });

            modelBuilder.Entity("backend.Models.VoteComment", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("CommentId")
                        .HasColumnType("int")
                        .HasColumnName("comment_id");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("create_at");

                    b.Property<bool>("DownVote")
                        .HasColumnType("bit")
                        .HasColumnName("down_vote");

                    b.Property<bool>("UpVote")
                        .HasColumnType("bit")
                        .HasColumnName("up_vote");

                    b.HasKey("UserId", "CommentId")
                        .HasName("PK__VoteComm__D7C76067C06255A7");

                    b.HasIndex("CommentId");

                    b.ToTable("VoteComment");
                });

            modelBuilder.Entity("backend.Models.VotePost", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("PostId")
                        .HasColumnType("int")
                        .HasColumnName("post_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<bool>("DownVote")
                        .HasColumnType("bit")
                        .HasColumnName("down_vote");

                    b.Property<bool>("UpVote")
                        .HasColumnType("bit")
                        .HasColumnName("up_vote");

                    b.HasKey("UserId", "PostId")
                        .HasName("PK__VotePost__CA534F79E6329B08");

                    b.HasIndex("PostId");

                    b.ToTable("VotePost");
                });

            modelBuilder.Entity("backend.Models.Category", b =>
                {
                    b.HasOne("backend.Models.User", "Admin")
                        .WithMany("Categories")
                        .HasForeignKey("AdminId")
                        .HasConstraintName("FKCategory311908")
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("backend.Models.CategoryTag", b =>
                {
                    b.HasOne("backend.Models.Category", "Category")
                        .WithMany("CategoryTags")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FKCategoryTa611140")
                        .IsRequired();

                    b.HasOne("backend.Models.Tag", "Tag")
                        .WithMany("CategoryTags")
                        .HasForeignKey("TagId")
                        .HasConstraintName("FKCategoryTa484641")
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("backend.Models.Comment", b =>
                {
                    b.HasOne("backend.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .HasConstraintName("FKComment632288")
                        .IsRequired();

                    b.HasOne("backend.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FKComment400844")
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.FollowUser", b =>
                {
                    b.HasOne("backend.Models.User", "Followed")
                        .WithMany("FollowUserFolloweds")
                        .HasForeignKey("FollowedId")
                        .HasConstraintName("FKFollowUser783758")
                        .IsRequired();

                    b.HasOne("backend.Models.User", "Follower")
                        .WithMany("FollowUserFollowers")
                        .HasForeignKey("FollowerId")
                        .HasConstraintName("FKFollowUser200833")
                        .IsRequired();

                    b.Navigation("Followed");

                    b.Navigation("Follower");
                });

            modelBuilder.Entity("backend.Models.Image", b =>
                {
                    b.HasOne("backend.Models.Post", "Post")
                        .WithMany("ImagePosts")
                        .HasForeignKey("PostId")
                        .HasConstraintName("FKImage400844")
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("backend.Models.Post", b =>
                {
                    b.HasOne("backend.Models.User", "Reviewer")
                        .WithMany("PostReviewers")
                        .HasForeignKey("ReviewerId")
                        .HasConstraintName("FKPost548405");

                    b.HasOne("backend.Models.User", "User")
                        .WithMany("PostUsers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FKPost990072")
                        .IsRequired();

                    b.Navigation("Reviewer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.PostCategory", b =>
                {
                    b.HasOne("backend.Models.Category", "Category")
                        .WithMany("PostCategories")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FKPostCatego136719")
                        .IsRequired();

                    b.HasOne("backend.Models.Post", "Post")
                        .WithMany("PostCategories")
                        .HasForeignKey("PostId")
                        .HasConstraintName("FKPostCatego519402")
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("backend.Models.PostList", b =>
                {
                    b.HasOne("backend.Models.SaveList", "SaveList")
                        .WithMany("PostLists")
                        .HasForeignKey("SaveListId")
                        .HasConstraintName("FKPostList365782")
                        .IsRequired();

                    b.HasOne("backend.Models.Post", "SavePost")
                        .WithMany("PostLists")
                        .HasForeignKey("SavePostId")
                        .HasConstraintName("FKPostList86128")
                        .IsRequired();

                    b.Navigation("SaveList");

                    b.Navigation("SavePost");
                });

            modelBuilder.Entity("backend.Models.PostTag", b =>
                {
                    b.HasOne("backend.Models.Post", "Post")
                        .WithMany("PostTags")
                        .HasForeignKey("PostId")
                        .HasConstraintName("FKPostTag716835")
                        .IsRequired();

                    b.HasOne("backend.Models.Tag", "Tag")
                        .WithMany("PostTags")
                        .HasForeignKey("TagId")
                        .HasConstraintName("FKPostTag277175")
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("backend.Models.ReportPost", b =>
                {
                    b.HasOne("backend.Models.User", "Admin")
                        .WithMany("ReportPostAdmins")
                        .HasForeignKey("AdminId")
                        .HasConstraintName("FKReportPost712211");

                    b.HasOne("backend.Models.Post", "Post")
                        .WithMany("ReportPosts")
                        .HasForeignKey("PostId")
                        .HasConstraintName("FKReportPost960109")
                        .IsRequired();

                    b.HasOne("backend.Models.User", "Reporter")
                        .WithMany("ReportPostReporters")
                        .HasForeignKey("ReporterId")
                        .HasConstraintName("FKReportPost680973")
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Post");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("backend.Models.SaveList", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithMany("SaveLists")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FKSaveList283598")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Tag", b =>
                {
                    b.HasOne("backend.Models.User", "Admin")
                        .WithMany("Tags")
                        .HasForeignKey("AdminId")
                        .HasConstraintName("FKTag383419")
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("backend.Models.UserCategory", b =>
                {
                    b.HasOne("backend.Models.Category", "Category")
                        .WithMany("UserCategories")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FKUserCatego136719")
                        .IsRequired();

                    b.HasOne("backend.Models.User", "User")
                        .WithMany("UserCategories")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FKUserCatego519402")
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.UserTag", b =>
                {
                    b.HasOne("backend.Models.Tag", "Tag")
                        .WithMany("UserTags")
                        .HasForeignKey("TagId")
                        .HasConstraintName("FKUserTag136719")
                        .IsRequired();

                    b.HasOne("backend.Models.User", "User")
                        .WithMany("UserTags")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FKUserTag519402")
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Video", b =>
                {
                    b.HasOne("backend.Models.Post", "Post")
                        .WithMany("VideoPosts")
                        .HasForeignKey("PostId")
                        .HasConstraintName("FKVideo280203")
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("backend.Models.VoteComment", b =>
                {
                    b.HasOne("backend.Models.Comment", "Comment")
                        .WithMany("VoteComments")
                        .HasForeignKey("CommentId")
                        .HasConstraintName("FKVoteCommen971268")
                        .IsRequired();

                    b.HasOne("backend.Models.User", "User")
                        .WithMany("VoteComments")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FKVoteCommen692680")
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.VotePost", b =>
                {
                    b.HasOne("backend.Models.Post", "Post")
                        .WithMany("VotePosts")
                        .HasForeignKey("PostId")
                        .HasConstraintName("FKVotePost439037")
                        .IsRequired();

                    b.HasOne("backend.Models.User", "User")
                        .WithMany("VotePosts")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FKVotePost207593")
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Category", b =>
                {
                    b.Navigation("CategoryTags");

                    b.Navigation("PostCategories");

                    b.Navigation("UserCategories");
                });

            modelBuilder.Entity("backend.Models.Comment", b =>
                {
                    b.Navigation("VoteComments");
                });

            modelBuilder.Entity("backend.Models.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("ImagePosts");

                    b.Navigation("PostCategories");

                    b.Navigation("PostLists");

                    b.Navigation("PostTags");

                    b.Navigation("ReportPosts");

                    b.Navigation("VideoPosts");

                    b.Navigation("VotePosts");
                });

            modelBuilder.Entity("backend.Models.SaveList", b =>
                {
                    b.Navigation("PostLists");
                });

            modelBuilder.Entity("backend.Models.Tag", b =>
                {
                    b.Navigation("CategoryTags");

                    b.Navigation("PostTags");

                    b.Navigation("UserTags");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Comments");

                    b.Navigation("FollowUserFolloweds");

                    b.Navigation("FollowUserFollowers");

                    b.Navigation("PostReviewers");

                    b.Navigation("PostUsers");

                    b.Navigation("ReportPostAdmins");

                    b.Navigation("ReportPostReporters");

                    b.Navigation("SaveLists");

                    b.Navigation("Tags");

                    b.Navigation("UserCategories");

                    b.Navigation("UserTags");

                    b.Navigation("VoteComments");

                    b.Navigation("VotePosts");
                });
#pragma warning restore 612, 618
        }
    }
}
